### ISSUE TITLE
Webpack 4?

### ISSUE THREAD

**Issue by josephliccini** [yeojz/filter-chunk-webpack-plugin#1]
Hi !

Thanks for writing this!

This plugin was just what our build needed! (it's a bit of a complex setup 😉 )

Are you planning webpack 4 support? Or does it work already in webpack 4? (haven't tried myself)

Thanks!
Joe

**Comment by yeojz** [comment]
Hi! @josephliccini 

Glad that it was of use! I first wrote this as I was working on a build that had complex setup as well.

I didn't try it before, but I took a look at the changes needed and went ahead and updated + released the plugin with Webpack 4 compatibility.

`npm install filter-chunk-webpack-plugin@^2.0.0`

Cheers!

**Comment by josephliccini** [comment]
Thanks! 😀
